name: C/C++ CI

on:
  push:
    branches:
    - actions

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: init vs studio (configure)
        # adapted from https://github.community/t5/GitHub-Actions/Windows-syntax-for-Run-path-with-spaces/m-p/30803#M569 
      run: |
        call "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\Common7\\tools\\vcvars64.bat"
        win32/configure.bat
        dir /s "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\Common7"
    - name: nmake
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\${{ matrix.vs }}\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set YACC=win_bison
        nmake up
        nmake
#    - name: make distcheck
#      run: make distcheck


