name: C/C++ CI

on:
  push:
    branches:
    - actions

jobs:
  build:

    runs-on: windows-latest

    ## copied verbatim from docs
    ## https://help.github.com/en/articles/workflow-syntax-for-github-actions#about-yaml-syntax-for-workflows
    ##
    # Example running a script using Windows cmd:
    steps:
      - uses: actions/checkout@master
      - name: install Qt
        run: |
            @echo on
            @prompt $G$S
            @echo --- Qt install cmd script %~dpnx0
            pushd %GITHUB_WORKSPACE%
            pushd tools
            curl -vLo qt-unified-windows-x86-online.exe http://download.qt.io/official_releases/online_installers/qt-unified-windows-x86-online.exe
            qt-unified-windows-x86-online.exe --verbose --script qt-installer-windows.qs
            
      #- name: install Win10 SDK
      #  run: |
      #      rem choco install windows-sdk-10
      #          :: fails with exit code 2008, see https://chocolatey.org/packages/windows-sdk-10.1#comment-4196624327
      #      pushd "%temp%"
      #      echo pwd: %cd%
      #      echo cmd: curl -o winsdksetup.exe https://download.microsoft.com/download/9/3/9/939441D4-6FBA-48EE-9EF7-402C1AA8B8A7/windowssdk/winsdksetup.exe
      #      curl -o winsdksetup.exe https://download.microsoft.com/download/9/3/9/939441D4-6FBA-48EE-9EF7-402C1AA8B8A7/windowssdk/winsdksetup.exe
      #      echo cmd: winsdksetup.exe /Quiet /NoRestart /Log windows-sdk-install.log
      #      winsdksetup.exe /Quiet /NoRestart /Log windows-sdk-install.log
      #      echo cmd: type windows-sdk-install.log
      #      type windows-sdk-install.log
            
      - name: install MS build tools
        run: choco install visualstudio2019buildtools visualstudio2019-workload-vctools

      - name: Set VS env
        run: |
            rem echo %PATH%
            pushd "C:/Program Files (x86)/Microsoft Visual Studio"
            echo %cd%            
            :: Uncomment to find all bats in this tree
            rem dir /s/b *.bat
            "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Auxiliary/Build/vcvars64.bat"
            cmake --version
            echo --- The build cmd goes here, when we figure out what that is ---
        shell: cmd
        
    # # Example running a script using PowerShell Core:
      # - name: Display the path
        # run: echo ${env:PATH}
        # shell: pwsh
    # # Example running a python script:
      # - name: Display the path
        # run: |
          # import os
          # print(os.environ['PATH'])
        # shell: python        
    
    # steps:
    #- uses: actions/checkout@v1
    # - name: init vs studio (configure)
        # adapted from https://github.community/t5/GitHub-Actions/Windows-syntax-for-Run-path-with-spaces/m-p/30803#M569 
      # run: |
        # cd "C:/Program Files (x86)/Microsoft Visual Studio/"
        # echo %cd%
        # rem dir /s/b vcvars*.bat
        # rem dir /s/b *.bat
        # echo dir /s/b "c:/Program Files (x86)/*.bat" >t.bat
        # t.bat
        # cd /
        # dir /s/b *.bat
    # - name: nmake
      # run: |
        # call "C:\Program Files (x86)\Microsoft Visual Studio\${{ matrix.vs }}\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        # set YACC=win_bison
        # nmake up
        # nmake
#    - name: make distcheck
#      run: make distcheck
